name: Build Containers for Prod & Push to Local Registry

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-front:
    name: Build and Deploy Front-end
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: bluewave-site:latest
        context: .
        load: true

    - name: Inspect
      run: |
        docker image inspect bluewave-site:latest

    - name: Docker Run
      run: |
        docker run -d --name site -p 3000:3000 bluewave-site:latest
    
    # - name: Docker Run
    #   uses: addnab/docker-run-action@v2
    #   with:
    #     image: bluewave-site:latest
    #     run: echo "Running image"
